var model = {
    vertex: [
        {name: "GV0"},
        {name: "GV1"},
        {name: "GV2"},
        {name: "GV3"}
    ],
    edges: [
        {name: "GE0", src:"GV2", trg: "GV2" },
        {name: "GE1", src:"GV2", trg: "GV3" },
        {name: "GE2", src:"GV2", trg: "GV0" },
        {name: "GE3", src:"GV2", trg: "GV0" },
        {name: "GE4", src:"GV3", trg: "GV2" },
        {name: "GE5", src:"GV3", trg: "GV1" },
        {name: "GE6", src:"GV2", trg: "GV0" },
        {name: "GE7", src:"GV2", trg: "GV1" }
    ]
};







var rules = [
    {
        name: "rule1",
        X: {vertex: [
            {name: "RV1", type: "GV3"},
            {name: "RV2", type: "GV2"},
            {name: "RV3", type: "GV0"},
            {name: "RV4", type: "GV2"},
            {name: "RV5", type: "GV1"},
            {name: "RV6", type: "GV0"},
            {name: "RV7", type: "GV3"},
            {name: "RV8", type: "GV1"},
            {name: "RV9", type: "GV2"},
            {name: "RV10", type: "GV0"},
            {name: "RV11", type: "GV2"},
            {name: "RV12", type: "GV3"},
            {name: "RV13", type: "GV2"},
            {name: "RV14", type: "GV3"},
            {name: "RV15", type: "GV2"},
            {name: "RV16", type: "GV1"},
            {name: "RV17", type: "GV3"},
            {name: "RV18", type: "GV1"},
            {name: "RV19", type: "GV1"},
            {name: "RV20", type: "GV2"},
            {name: "RV21", type: "GV2"},
            {name: "RV22", type: "GV1"},
            {name: "RV23", type: "GV0"},
            {name: "RV24", type: "GV1"},
            {name: "RV25", type: "GV3"},
            {name: "RV26", type: "GV2"},
            {name: "RV27", type: "GV1"},
            {name: "RV28", type: "GV0"},
            {name: "RV29", type: "GV0"},
            {name: "RV30", type: "GV1"},
            {name: "RV31", type: "GV3"},
            {name: "RV32", type: "GV2"},
            {name: "RV33", type: "GV3"},
            {name: "RV34", type: "GV1"},
            {name: "RV35", type: "GV2"},
            {name: "RV36", type: "GV2"},
            {name: "RV37", type: "GV3"},
            {name: "RV38", type: "GV2"},
            {name: "RV39", type: "GV0"},
            {name: "RV40", type: "GV1"},
            {name: "RV41", type: "GV0"},
            {name: "RV42", type: "GV2"},
            {name: "RV43", type: "GV3"},
            {name: "RV44", type: "GV1"},
            {name: "RV45", type: "GV0"},
            {name: "RV46", type: "GV2"},
            {name: "RV47", type: "GV1"},
            {name: "RV48", type: "GV2"},
            {name: "RV49", type: "GV2"},
            {name: "RV50", type: "GV2"},
            {name: "RV51", type: "GV1"},
            {name: "RV52", type: "GV0"},
            {name: "RV53", type: "GV1"}
        ],
            edges: [
                {name: "RE1", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE2", src:"RV2", trg: "RV3", type: "GE6" },
                {name: "RE3", src:"RV2", trg: "RV3", type: "GE6" },
                {name: "RE4", src:"RV4", trg: "RV5", type: "GE7" },
                {name: "RE5", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE6", src:"RV2", trg: "RV2", type: "GE0" },
                {name: "RE7", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE8", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE9", src:"RV2", trg: "RV4", type: "GE0" },
                {name: "RE10", src:"RV9", trg: "RV10", type: "GE6" },
                {name: "RE11", src:"RV11", trg: "RV2", type: "GE0" },
                {name: "RE12", src:"RV2", trg: "RV12", type: "GE1" },
                {name: "RE13", src:"RV2", trg: "RV4", type: "GE0" },
                {name: "RE14", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE15", src:"RV9", trg: "RV3", type: "GE3" },
                {name: "RE16", src:"RV2", trg: "RV6", type: "GE2" },
                {name: "RE17", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE18", src:"RV2", trg: "RV6", type: "GE2" },
                {name: "RE19", src:"RV4", trg: "RV9", type: "GE0" },
                {name: "RE20", src:"RV4", trg: "RV6", type: "GE2" },
                {name: "RE21", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE22", src:"RV1", trg: "RV9", type: "GE4" },
                {name: "RE23", src:"RV13", trg: "RV4", type: "GE0" },
                {name: "RE24", src:"RV14", trg: "RV2", type: "GE4" },
                {name: "RE25", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE26", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE27", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE28", src:"RV9", trg: "RV3", type: "GE6" },
                {name: "RE29", src:"RV4", trg: "RV10", type: "GE6" },
                {name: "RE30", src:"RV4", trg: "RV3", type: "GE6" },
                {name: "RE31", src:"RV2", trg: "RV2", type: "GE0" },
                {name: "RE32", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE33", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE34", src:"RV4", trg: "RV2", type: "GE0" },
                {name: "RE35", src:"RV9", trg: "RV10", type: "GE3" },
                {name: "RE36", src:"RV4", trg: "RV15", type: "GE0" },
                {name: "RE37", src:"RV4", trg: "RV3", type: "GE6" },
                {name: "RE38", src:"RV9", trg: "RV16", type: "GE7" },
                {name: "RE39", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE40", src:"RV2", trg: "RV7", type: "GE1" },
                {name: "RE41", src:"RV4", trg: "RV2", type: "GE0" },
                {name: "RE42", src:"RV14", trg: "RV8", type: "GE5" },
                {name: "RE43", src:"RV9", trg: "RV1", type: "GE1" },
                {name: "RE44", src:"RV11", trg: "RV3", type: "GE3" },
                {name: "RE45", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE46", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE47", src:"RV4", trg: "RV6", type: "GE6" },
                {name: "RE48", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE49", src:"RV2", trg: "RV17", type: "GE1" },
                {name: "RE50", src:"RV1", trg: "RV8", type: "GE5" },
                {name: "RE51", src:"RV4", trg: "RV6", type: "GE2" },
                {name: "RE52", src:"RV4", trg: "RV1", type: "GE1" },
                {name: "RE53", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE54", src:"RV4", trg: "RV18", type: "GE7" },
                {name: "RE55", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE56", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE57", src:"RV1", trg: "RV19", type: "GE5" },
                {name: "RE58", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE59", src:"RV4", trg: "RV3", type: "GE2" },
                {name: "RE60", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE61", src:"RV4", trg: "RV12", type: "GE1" },
                {name: "RE62", src:"RV9", trg: "RV6", type: "GE6" },
                {name: "RE63", src:"RV1", trg: "RV5", type: "GE5" },
                {name: "RE64", src:"RV12", trg: "RV2", type: "GE4" },
                {name: "RE65", src:"RV4", trg: "RV16", type: "GE7" },
                {name: "RE66", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE67", src:"RV7", trg: "RV4", type: "GE4" },
                {name: "RE68", src:"RV12", trg: "RV20", type: "GE4" },
                {name: "RE69", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE70", src:"RV2", trg: "RV7", type: "GE1" },
                {name: "RE71", src:"RV17", trg: "RV5", type: "GE5" },
                {name: "RE74", src:"RV13", trg: "RV6", type: "GE3" },
                {name: "RE75", src:"RV1", trg: "RV2", type: "GE4" }
            ]
        },
        L: {vertex: [
            {name: "RV1", type: "GV3"},
            {name: "RV2", type: "GV2"},
            {name: "RV3", type: "GV0"},
            {name: "RV4", type: "GV2"},
            {name: "RV5", type: "GV1"},
            {name: "RV6", type: "GV0"},
            {name: "RV7", type: "GV3"},
            {name: "RV8", type: "GV1"},
            {name: "RV9", type: "GV2"},
            {name: "RV10", type: "GV0"},
            {name: "RV11", type: "GV2"},
            {name: "RV12", type: "GV3"},
            {name: "RV13", type: "GV2"},
            {name: "RV14", type: "GV3"},
            {name: "RV15", type: "GV2"},
            {name: "RV16", type: "GV1"},
            {name: "RV17", type: "GV3"},
            {name: "RV18", type: "GV1"},
            {name: "RV19", type: "GV1"},
            {name: "RV20", type: "GV2"},
            {name: "RV21", type: "GV2"},
            {name: "RV22", type: "GV1"},
            {name: "RV23", type: "GV0"},
            {name: "RV24", type: "GV1"},
            {name: "RV25", type: "GV3"},
            {name: "RV26", type: "GV2"},
            {name: "RV27", type: "GV1"},
            {name: "RV28", type: "GV0"},
            {name: "RV29", type: "GV0"},
            {name: "RV30", type: "GV1"},
            {name: "RV31", type: "GV3"},
            {name: "RV32", type: "GV2"},
            {name: "RV33", type: "GV3"},
            {name: "RV34", type: "GV1"},
            {name: "RV35", type: "GV2"},
            {name: "RV36", type: "GV2"},
            {name: "RV37", type: "GV3"},
            {name: "RV38", type: "GV2"},
            {name: "RV39", type: "GV0"},
            {name: "RV40", type: "GV1"},
            {name: "RV41", type: "GV0"},
            {name: "RV42", type: "GV2"},
            {name: "RV43", type: "GV3"},
            {name: "RV44", type: "GV1"},
            {name: "RV45", type: "GV0"},
            {name: "RV46", type: "GV2"},
            {name: "RV47", type: "GV1"},
            {name: "RV48", type: "GV2"},
            {name: "RV49", type: "GV2"},
            {name: "RV50", type: "GV2"}
        ],
            edges: [
                {name: "RE1", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE2", src:"RV2", trg: "RV3", type: "GE6" },
                {name: "RE3", src:"RV2", trg: "RV3", type: "GE6" },
                {name: "RE4", src:"RV4", trg: "RV5", type: "GE7" },
                {name: "RE5", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE6", src:"RV2", trg: "RV2", type: "GE0" },
                {name: "RE7", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE8", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE9", src:"RV2", trg: "RV4", type: "GE0" },
                {name: "RE10", src:"RV9", trg: "RV10", type: "GE6" },
                {name: "RE11", src:"RV11", trg: "RV2", type: "GE0" },
                {name: "RE12", src:"RV2", trg: "RV12", type: "GE1" },
                {name: "RE13", src:"RV2", trg: "RV4", type: "GE0" },
                {name: "RE14", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE15", src:"RV9", trg: "RV3", type: "GE3" },
                {name: "RE16", src:"RV2", trg: "RV6", type: "GE2" },
                {name: "RE17", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE18", src:"RV2", trg: "RV6", type: "GE2" },
                {name: "RE19", src:"RV4", trg: "RV9", type: "GE0" },
                {name: "RE20", src:"RV4", trg: "RV6", type: "GE2" },
                {name: "RE21", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE22", src:"RV1", trg: "RV9", type: "GE4" },
                {name: "RE23", src:"RV13", trg: "RV4", type: "GE0" },
                {name: "RE24", src:"RV14", trg: "RV2", type: "GE4" },
                {name: "RE25", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE26", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE27", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE28", src:"RV9", trg: "RV3", type: "GE6" },
                {name: "RE29", src:"RV4", trg: "RV10", type: "GE6" },
                {name: "RE30", src:"RV4", trg: "RV3", type: "GE6" },
                {name: "RE31", src:"RV2", trg: "RV2", type: "GE0" },
                {name: "RE32", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE33", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE34", src:"RV4", trg: "RV2", type: "GE0" },
                {name: "RE35", src:"RV9", trg: "RV10", type: "GE3" },
                {name: "RE36", src:"RV4", trg: "RV15", type: "GE0" },
                {name: "RE37", src:"RV4", trg: "RV3", type: "GE6" },
                {name: "RE38", src:"RV9", trg: "RV16", type: "GE7" },
                {name: "RE39", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE40", src:"RV2", trg: "RV7", type: "GE1" },
                {name: "RE41", src:"RV4", trg: "RV2", type: "GE0" },
                {name: "RE42", src:"RV14", trg: "RV8", type: "GE5" },
                {name: "RE43", src:"RV9", trg: "RV1", type: "GE1" },
                {name: "RE44", src:"RV11", trg: "RV3", type: "GE3" },
                {name: "RE45", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE46", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE47", src:"RV4", trg: "RV6", type: "GE6" },
                {name: "RE48", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE49", src:"RV2", trg: "RV17", type: "GE1" },
                {name: "RE50", src:"RV1", trg: "RV8", type: "GE5" },
                {name: "RE51", src:"RV4", trg: "RV6", type: "GE2" },
                {name: "RE52", src:"RV4", trg: "RV1", type: "GE1" },
                {name: "RE53", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE54", src:"RV4", trg: "RV18", type: "GE7" },
                {name: "RE55", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE56", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE57", src:"RV1", trg: "RV19", type: "GE5" },
                {name: "RE58", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE59", src:"RV4", trg: "RV3", type: "GE2" },
                {name: "RE60", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE61", src:"RV4", trg: "RV12", type: "GE1" },
                {name: "RE62", src:"RV9", trg: "RV6", type: "GE6" },
                {name: "RE63", src:"RV1", trg: "RV5", type: "GE5" },
                {name: "RE64", src:"RV12", trg: "RV2", type: "GE4" },
                {name: "RE65", src:"RV4", trg: "RV16", type: "GE7" },
                {name: "RE66", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE67", src:"RV7", trg: "RV4", type: "GE4" },
                {name: "RE68", src:"RV12", trg: "RV20", type: "GE4" },
                {name: "RE69", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE70", src:"RV2", trg: "RV7", type: "GE1" }
            ]
        },
        K: {vertex: [
            {name: "RV1", type: "GV3"},
            {name: "RV2", type: "GV2"},
            {name: "RV3", type: "GV0"},
            {name: "RV5", type: "GV1"},
            {name: "RV6", type: "GV0"},
            {name: "RV7", type: "GV3"},
            {name: "RV8", type: "GV1"},
            {name: "RV9", type: "GV2"},
            {name: "RV10", type: "GV0"},
            {name: "RV11", type: "GV2"},
            {name: "RV12", type: "GV3"},
            {name: "RV13", type: "GV2"},
            {name: "RV14", type: "GV3"},
            {name: "RV15", type: "GV2"},
            {name: "RV17", type: "GV3"},
            {name: "RV19", type: "GV1"},
            {name: "RV20", type: "GV2"},
            {name: "RV21", type: "GV2"},
            {name: "RV22", type: "GV1"},
            {name: "RV23", type: "GV0"},
            {name: "RV25", type: "GV3"},
            {name: "RV26", type: "GV2"},
            {name: "RV27", type: "GV1"},
            {name: "RV28", type: "GV0"},
            {name: "RV29", type: "GV0"},
            {name: "RV30", type: "GV1"},
            {name: "RV31", type: "GV3"},
            {name: "RV32", type: "GV2"},
            {name: "RV33", type: "GV3"},
            {name: "RV34", type: "GV1"},
            {name: "RV35", type: "GV2"},
            {name: "RV36", type: "GV2"},
            {name: "RV37", type: "GV3"},
            {name: "RV39", type: "GV0"},
            {name: "RV40", type: "GV1"},
            {name: "RV41", type: "GV0"},
            {name: "RV42", type: "GV2"},
            {name: "RV43", type: "GV3"},
            {name: "RV44", type: "GV1"},
            {name: "RV45", type: "GV0"},
            {name: "RV46", type: "GV2"},
            {name: "RV47", type: "GV1"},
            {name: "RV48", type: "GV2"},
            {name: "RV49", type: "GV2"},
            {name: "RV50", type: "GV2"}
        ],
            edges: [
                {name: "RE1", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE2", src:"RV2", trg: "RV3", type: "GE6" },
                {name: "RE3", src:"RV2", trg: "RV3", type: "GE6" },
                {name: "RE5", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE6", src:"RV2", trg: "RV2", type: "GE0" },
                {name: "RE7", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE8", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE10", src:"RV9", trg: "RV10", type: "GE6" },
                {name: "RE11", src:"RV11", trg: "RV2", type: "GE0" },
                {name: "RE12", src:"RV2", trg: "RV12", type: "GE1" },
                {name: "RE14", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE15", src:"RV9", trg: "RV3", type: "GE3" },
                {name: "RE16", src:"RV2", trg: "RV6", type: "GE2" },
                {name: "RE17", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE18", src:"RV2", trg: "RV6", type: "GE2" },
                {name: "RE21", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE22", src:"RV1", trg: "RV9", type: "GE4" },
                {name: "RE24", src:"RV14", trg: "RV2", type: "GE4" },
                {name: "RE25", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE26", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE27", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE28", src:"RV9", trg: "RV3", type: "GE6" },
                {name: "RE31", src:"RV2", trg: "RV2", type: "GE0" },
                {name: "RE32", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE33", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE35", src:"RV9", trg: "RV10", type: "GE3" },
                {name: "RE39", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE40", src:"RV2", trg: "RV7", type: "GE1" },
                {name: "RE42", src:"RV14", trg: "RV8", type: "GE5" },
                {name: "RE43", src:"RV9", trg: "RV1", type: "GE1" },
                {name: "RE44", src:"RV11", trg: "RV3", type: "GE3" },
                {name: "RE45", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE46", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE48", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE49", src:"RV2", trg: "RV17", type: "GE1" },
                {name: "RE50", src:"RV1", trg: "RV8", type: "GE5" },
                {name: "RE53", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE55", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE56", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE57", src:"RV1", trg: "RV19", type: "GE5" },
                {name: "RE58", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE60", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE62", src:"RV9", trg: "RV6", type: "GE6" },
                {name: "RE63", src:"RV1", trg: "RV5", type: "GE5" },
                {name: "RE64", src:"RV12", trg: "RV2", type: "GE4" },
                {name: "RE66", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE68", src:"RV12", trg: "RV20", type: "GE4" },
                {name: "RE69", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE70", src:"RV2", trg: "RV7", type: "GE1" }
            ]
        },
        R: {vertex: [
            {name: "RV1", type: "GV3"},
            {name: "RV2", type: "GV2"},
            {name: "RV3", type: "GV0"},
            {name: "RV5", type: "GV1"},
            {name: "RV6", type: "GV0"},
            {name: "RV7", type: "GV3"},
            {name: "RV8", type: "GV1"},
            {name: "RV9", type: "GV2"},
            {name: "RV10", type: "GV0"},
            {name: "RV11", type: "GV2"},
            {name: "RV12", type: "GV3"},
            {name: "RV13", type: "GV2"},
            {name: "RV14", type: "GV3"},
            {name: "RV15", type: "GV2"},
            {name: "RV17", type: "GV3"},
            {name: "RV19", type: "GV1"},
            {name: "RV20", type: "GV2"},
            {name: "RV21", type: "GV2"},
            {name: "RV22", type: "GV1"},
            {name: "RV23", type: "GV0"},
            {name: "RV25", type: "GV3"},
            {name: "RV26", type: "GV2"},
            {name: "RV27", type: "GV1"},
            {name: "RV28", type: "GV0"},
            {name: "RV29", type: "GV0"},
            {name: "RV30", type: "GV1"},
            {name: "RV31", type: "GV3"},
            {name: "RV32", type: "GV2"},
            {name: "RV33", type: "GV3"},
            {name: "RV34", type: "GV1"},
            {name: "RV35", type: "GV2"},
            {name: "RV36", type: "GV2"},
            {name: "RV37", type: "GV3"},
            {name: "RV39", type: "GV0"},
            {name: "RV40", type: "GV1"},
            {name: "RV41", type: "GV0"},
            {name: "RV42", type: "GV2"},
            {name: "RV43", type: "GV3"},
            {name: "RV44", type: "GV1"},
            {name: "RV45", type: "GV0"},
            {name: "RV46", type: "GV2"},
            {name: "RV47", type: "GV1"},
            {name: "RV48", type: "GV2"},
            {name: "RV49", type: "GV2"},
            {name: "RV50", type: "GV2"},
            {name: "RV51", type: "GV1"}
        ],
            edges: [
                {name: "RE1", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE2", src:"RV2", trg: "RV3", type: "GE6" },
                {name: "RE3", src:"RV2", trg: "RV3", type: "GE6" },
                {name: "RE5", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE6", src:"RV2", trg: "RV2", type: "GE0" },
                {name: "RE7", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE8", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE10", src:"RV9", trg: "RV10", type: "GE6" },
                {name: "RE11", src:"RV11", trg: "RV2", type: "GE0" },
                {name: "RE12", src:"RV2", trg: "RV12", type: "GE1" },
                {name: "RE14", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE15", src:"RV9", trg: "RV3", type: "GE3" },
                {name: "RE16", src:"RV2", trg: "RV6", type: "GE2" },
                {name: "RE17", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE18", src:"RV2", trg: "RV6", type: "GE2" },
                {name: "RE21", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE22", src:"RV1", trg: "RV9", type: "GE4" },
                {name: "RE24", src:"RV14", trg: "RV2", type: "GE4" },
                {name: "RE25", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE26", src:"RV7", trg: "RV2", type: "GE4" },
                {name: "RE27", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE28", src:"RV9", trg: "RV3", type: "GE6" },
                {name: "RE31", src:"RV2", trg: "RV2", type: "GE0" },
                {name: "RE32", src:"RV1", trg: "RV2", type: "GE4" },
                {name: "RE33", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE35", src:"RV9", trg: "RV10", type: "GE3" },
                {name: "RE39", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE40", src:"RV2", trg: "RV7", type: "GE1" },
                {name: "RE42", src:"RV14", trg: "RV8", type: "GE5" },
                {name: "RE43", src:"RV9", trg: "RV1", type: "GE1" },
                {name: "RE44", src:"RV11", trg: "RV3", type: "GE3" },
                {name: "RE45", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE46", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE48", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE49", src:"RV2", trg: "RV17", type: "GE1" },
                {name: "RE50", src:"RV1", trg: "RV8", type: "GE5" },
                {name: "RE53", src:"RV2", trg: "RV6", type: "GE6" },
                {name: "RE55", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE56", src:"RV2", trg: "RV8", type: "GE7" },
                {name: "RE57", src:"RV1", trg: "RV19", type: "GE5" },
                {name: "RE58", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE60", src:"RV2", trg: "RV1", type: "GE1" },
                {name: "RE62", src:"RV9", trg: "RV6", type: "GE6" },
                {name: "RE63", src:"RV1", trg: "RV5", type: "GE5" },
                {name: "RE64", src:"RV12", trg: "RV2", type: "GE4" },
                {name: "RE66", src:"RV2", trg: "RV3", type: "GE2" },
                {name: "RE68", src:"RV12", trg: "RV20", type: "GE4" },
                {name: "RE69", src:"RV2", trg: "RV5", type: "GE7" },
                {name: "RE70", src:"RV2", trg: "RV7", type: "GE1" },
                {name: "RE71", src:"RV17", trg: "RV5", type: "GE5" },
                {name: "RE72", src:"RV9", trg: "RV2", type: "GE0" },
                {name: "RE73", src:"RV12", trg: "RV5", type: "GE5" }
            ]
        }
    }
];
